### ISSUE TITLE
Configs

### ISSUE THREAD

**Issue by ImWhiff** [kwpugh/Gobber_mod_fabric#8]
Would it be possible to add the option in the configs to configure axe damage and speed separate from the sword? It would be great if I could adjust the axe damage to be not the same as sword damage.

Perhaps some other things such as modifying the duration of the lingering effect of  enablEndArrowCloud, setting enableEffectsGobberArrow to true would only give poison effect rather than all 3, able to configure Nether bow default have flame like the Nether sword has fire aspect (enableNetherSwordPerks), the option to add cooldown to ring of Sunshine etc.

I would be very happy if I could just configure the axe stats separate from the sword. Regardless, thank you for your time whether any of this would be possible or not.

**Comment by kwpugh** [comment]
I will take a look at that when I return to modding in May

**Comment by ImWhiff** [comment]
Awesome. I'm looking forward to it!

**Comment by kwpugh** [comment]
Lots of ideas there that I have added to me ideas sheet locally.

I have add config options for the gobber swords, axes, and paxels (I consider it a weapon like the axe) that allow you to set its base attack damage that gets added to the tool-wide attack damage config number.  I don't want to expose individual tool speeds because mojang uses negative numbers for the scaling of the different tools.  This should provide you and others the ability to adjust the sword and axe attack damages to your needs.

**Comment by kwpugh** [comment]
Note, this is starting in 1.20.6
